AllCops:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - !ruby/regexp /old_and_unused\.rb$/
    - "spec/**"

Rails:
  Enabled: true

# Commonly used screens these days easily fit more than 80 characters.
Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 1500

Style/ClassAndModuleChildren:
  Exclude:
    - "app/controllers/users/omniauth_callbacks_controller.rb"

Metrics/AbcSize:
  Max: 16
